name: Test and Build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
        django: ['1.11.*', '2.0.*', '2.1.*', '2.2.*', '3.0.*', '3.1.*', '3.2.*']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
        pip install django==${{ matrix.django }}
        pip install -e .[test]
    - name: Run tests
      run: make
    - uses: codecov/codecov-action@v1.0.3
      timeout-minutes: 1
      continue-on-error: true
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./.coverage
